function k(b,a,c,d){b.i.ta(b.V,a,c,d,void 0)}function p(b,a,c,d){b.i.A?k(b,a,c,d):b.i.yb()._OnMessageFromDOM({type:"event",component:b.V,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.i.h(b.V,a,c)}function q(b,a){for(const [c,d]of a)aa(b,c,d)}window.S=class{constructor(b,a){this.i=b;this.V=a}Na(){}};window.pb=class{constructor(b){this.Ya=b;this.Kb=5;this.O=-1;this.ka=-Infinity;this.Pb=()=>{this.O=-1;this.ka=Date.now();this.W=!0;this.Ya();this.W=!1};this.Za=this.W=!1}};
"use strict";function ba(b,a){const c=a.elementId,d=b.ea(c,a);b.s.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");a=b.va(d);a.addEventListener("focus",()=>{r(b,"elem-focused",c)});a.addEventListener("blur",()=>{r(b,"elem-blurred",c)});b.ia&&document.body.appendChild(d)}function t(b,a,c){aa(b,a,d=>{const e=b.s.get(d.elementId);return c(e,d)})}function r(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}function v(b,a,c,d){d||(d={});d.elementId=c;p(b,a,d)}
window.ra=class extends self.S{constructor(b,a){super(b,a);this.s=new Map;this.ia=!0;q(this,[["create",c=>ba(this,c)],["destroy",c=>{c=c.elementId;const d=this.s.get(c);this.ia&&d.parentElement.removeChild(d);this.s.delete(c)}],["set-visible",c=>{this.ia&&(this.s.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.ia){var d=this.s.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=c.height+"px";c=c.fontSize;
null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{const d=this.s.get(c.elementId);this.G(d,c)}],["focus",c=>this.za(c)],["set-css-style",c=>{const d=this.s.get(c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{this.s.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.s.get(c.elementId).removeAttribute(c.name)}]]);t(this,"get-element",c=>c)}ea(){throw Error("required override");}G(){throw Error("required override");
}va(b){return b}za(b){const a=this.va(this.s.get(b.elementId));b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent);let da=0;
function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ub?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.Yb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let y=new Audio;
const ia={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let A=0;window.RealFile=window.File;const B=[],C=new Map,D=new Map;let la=0;const ma=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ma.push(b)};const na=new Set(["cordova","playable-ad","instant-games"]);let oa=!1;
window.u=class b{constructor(a){this.A=a.$b;this.Z=null;this.m="";this.M=a.Xb;this.da={};this.Ha=this.P=null;this.ja=[];this.j=this.ba=null;this.cb=!1;this.X=null;this.L=-1;this.Ob=()=>this.Fb();this.gb=[];this.g=a.hb;this.Fa="file"===location.protocol.substr(0,4);!this.A||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.A=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.A=!1;if("cordova"===this.g&&this.A)if(w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.A=!1)}else this.A=!1;this.la=this.C=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime","cordova-fetch-local-file",c=>this.Bb(c));this.h("runtime","create-job-worker",()=>this.Cb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Sa(a)):this.Sa(a)}mb(){return ca&&
"cordova"===this.g}sa(){const a=navigator.userAgent;return ca&&na.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}kb(){return w}Pa(){return w&&na.has(this.g)}async Sa(a){"macos-wkwebview"===this.g&&this.Ba({type:"ready"});if("playable-ad"===this.g){this.C=self.c3_base64files;this.la={};await this.ub();for(let d=0,e=a.R.length;d<e;++d){var c=a.R[d];this.la.hasOwnProperty(c)?a.R[d]={Ub:!0,Yb:this.la[c]}:this.C.hasOwnProperty(c)&&(a.R[d]=URL.createObjectURL(this.C[c]))}}a.Wb?this.m=
a.Wb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.bc&&(this.da=a.bc);c=new MessageChannel;this.Z=c.port1;this.Z.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Eb(d));this.X=new self.nb(this);await pa(this.X);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,
e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.A?await this.Ab(a,c.port2):await this.zb(a,c.port2)}wa(a){a=this.da.hasOwnProperty(a)?this.da[a]:a.endsWith("/workermain.js")&&this.da.hasOwnProperty("workermain.js")?this.da["workermain.js"]:"playable-ad"===this.g&&this.C.hasOwnProperty(a)?this.C[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qa(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===
this.g&&this.Fa)return a=await this.pa(d.Tb?a:this.M+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}B(){return Math.max(window.innerWidth,1)}v(){return Math.max(window.innerHeight,1)}Ra(a){var c=this.m,d=location.href,e=this.B(),f=this.v(),g=window.devicePixelRatio,
h=b.T(),l=a.ic,m=window.cr_previewImageBlobs||this.C,n=window.cr_previewProjectFileBlobs,Ea=window.cr_previewProjectFiles,Fa=window.fc||"";a=a.hb;var Ga=(new URLSearchParams(self.location.search)).has("debug"),O=this.X;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:Ea,swClientId:Fa,exportType:a,isDebug:Ga,ife:!!self.hc,jobScheduler:{inputPort:O.Ea,outputPort:O.Ja,
maxNumWorkers:O.Mb},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.M+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.M+"opus.wasm.wasm",isFileProtocol:this.Fa,isiOSCordova:this.mb(),isiOSWebView:this.sa(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ab(a,c){const d=this.wa(a.ac);"preview"===this.g?(this.P=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.P.removeEventListener("message",
m);n.data&&"ok"===n.data.type?h():l()};this.P.addEventListener("message",m);this.P.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.P=await this.qa(d,this.m,{type:"module",name:"Runtime",Tb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.Ma||[],g=a.R;f=await Promise.all(f.map(h=>
this.J(h)));g=await Promise.all(g.map(h=>this.J(h)));if("cordova"===this.g)for(let h=0,l=a.oa.length;h<l;++h){const m=a.oa[h],n=m[0];if(n===a.La||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.J(n)}this.P.postMessage(Object.assign(this.Ra(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.oa,mainProjectScript:a.La,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...qa(this.X)]);this.ja=B.map(h=>
new h(this));this.Qa();sa(this.ba);self.c3_callFunction=(h,l)=>{var m=this.ba;return m.i.ob(m.V,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ta("runtime","go-to-last-error-script"))}async zb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.ja=B.map(g=>new g(this));this.Qa();var d=a.R.map(g=>"string"===typeof g?(new URL(g,
this.m)).toString():g);Array.isArray(a.Ma)&&d.unshift(...a.Ma);d=await Promise.all(d.map(g=>this.J(g)));await Promise.all(d.map(g=>x(g)));d=self.C3_ProjectScriptsStatus;const e=a.La,f=a.oa;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.J(h),await x(h),"preview"!==this.g||d[g]||this.Ua(g,"main script did not run to completion")}catch(l){this.Ua(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.J(h),await x(h);"preview"===this.g&&"object"!==typeof self.cc.dc?
(this.ga(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ra(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:ma}),sa(this.ba),this.Ta(),this.Ha=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ha,a))}Ua(a,c){this.ga();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ta(){this.ga()}ga(){const a=window.Rb;a&&(a.parentElement.removeChild(a),window.Rb=null)}async Cb(){const a=await ta(this.X);return{outputPort:a,transferables:[a]}}yb(){if(this.A)throw Error("not available in worker mode");return this.Ha}ta(a,c,d,e,f){this.Z.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}ob(a,c){const d=la++,e=new Promise((f,g)=>{D.set(d,{resolve:f,reject:g})});this.Z.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Db(a);if("result"===c)this.Gb(a);else if("runtime-ready"===c)this.Hb();else if("alert-error"===c)this.ga(),alert(a.message);else if("creating-runtime"===c)this.Ta();else throw Error(`unknown message '${c}'`);}Db(a){const c=a.component,
d=a.handler,e=a.data,f=a.responseId;if(a=C.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.fa(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.fa(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.fa(f,!1,""+h)}):this.fa(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}fa(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Z.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Gb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=D.get(c);d?e.resolve(a):e.reject(a);D.delete(c)}h(a,c,d){let e=C.get(a);e||(e=new Map,C.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static F(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}Qa(){for(const a of this.ja)if("runtime"===a.V){this.ba=a;return}throw Error("cannot find runtime DOM handler");
}Eb(a){this.ta("debugger","message",a)}Hb(){for(const a of this.ja)a.Na()}static T(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||oa)}static ha(a){oa=!!a}Va(){-1===this.L&&this.gb.length&&(this.L=requestAnimationFrame(this.Ob))}sb(){-1!==this.L&&(cancelAnimationFrame(this.L),this.L=-1)}Fb(){this.L=-1;for(const a of this.gb)a();this.Va()}Aa(){this.ba.Aa()}qb(){this.cb=!0}jb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===
a.substr(0,5)}lb(a){return!this.jb(a)}async J(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Fa&&this.lb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.pa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Bb(a){const c=a.filename;switch(a.as){case "text":return await this.ib(c);case "buffer":return await this.pa(c);default:throw Error("unsupported type");}}Oa(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,
e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ib(a){a=await this.Oa(a);return await ja(a)}ua(){if(z.length&&!(8<=A)){A++;var a=z.shift();this.vb(a.filename,a.Zb,a.Sb)}}pa(a){return new Promise((c,d)=>{z.push({filename:a,Zb:e=>{A--;this.ua();c(e)},Sb:e=>{A--;this.ua();d(e)}});this.ua()})}async vb(a,c,d){try{const e=await this.Oa(a),f=await ka(e);c(f)}catch(e){d(e)}}Ba(a){if("windows-webview2"===this.g)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===
this.g)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ub(){const a=[];for(const [c,d]of Object.entries(this.C))a.push(this.tb(c,d));await Promise.all(a)}async tb(a,c){if("object"===typeof c)this.C[a]=new Blob([c.str],{type:c.type}),this.la[a]=c.str;else{let d=await this.xb(c);d||(d=this.wb(c));this.C[a]=d}}async xb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}wb(a){a=this.Ib(a);return this.rb(a.data,a.Vb)}Ib(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Vb:a,data:d}}rb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const E=self.u;function ua(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},G={dispatchRuntimeEvent:!0};
function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function H(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}
function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await H(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await H(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await H(b)}
function I(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ba=new Set(["input","textarea","datalist","select"]),Ca=new Set(["canvas","body","html"]);function J(b){Ca.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Da(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await H(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let K=!1;document.addEventListener("pause",()=>K=!0);document.addEventListener("resume",()=>K=!1);function sa(b){b.ab=!0;b.Ga=b.i.B();b.Y=b.i.v()}async function Ha(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ia(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ja(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ka(b){self.setTimeout(()=>{b.$a=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>L(b,!0)),document.addEventListener("resume",()=>L(b,!1))):document.addEventListener("visibilitychange",()=>L(b,document.hidden));return{isSuspended:!(!document.hidden&&!K)}}
function La(b){b.Xa||(b.Xa=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function Ma(b){b.Wa||(b.Wa=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function Na(b){await xa(b.url)}
function Oa(b,a){b.bb=a.message;-1===b.Da&&(b.Da=setTimeout(()=>{b.Da=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.bb)},250))}function M(b){if(!b.l){var a=E.T();a&&"any"!==b.Ka&&Pa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.B(),innerHeight:b.v()})}}function N(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:E.T(),innerWidth:b.B(),innerHeight:b.v()})}
function L(b,a){a?b.i.sb():b.i.Va();k(b,"visibilitychange",{hidden:a})}function Qa(b,a,c){"Backspace"===c.key&&J(c);if(!b.l){var d=va.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F)}}
function P(b,a,c,d){b.l||ua(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Q(b){window!==window.top&&window.focus();Ra(b.target)&&document.activeElement&&!Ra(document.activeElement)&&document.activeElement.blur()}
function R(b,a,c){if(!b.l){if(b.aa&&"pointermove"!==a){var d=b.aa;d.W||(-1!==d.O&&(self.clearTimeout(d.O),d.O=-1),d.ka=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.$);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:(c.movementX||0)+b.ma,movementY:(c.movementY||0)+b.na,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||
0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},F);b.ma=0;b.na=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),P(b,d,c,wa),b.$=c.buttons)}}
function T(b,a,c){if(!b.l&&!ua(c)){var d=b.$;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.o,pageX:c.pageX,pageY:c.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},F);b.$=c.buttons;P(b,c.type,c,wa)}}
function U(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.o,pageX:f.pageX,pageY:f.pageY+b.o,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
F)}}function V(b,a,c){document.body.style.transform="";b.o=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.o=a))}}function Sa(b,a,c,d){const e=b.B(),f=b.v();b.N=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.T()}):10>d&&Ta(b,e,f,d+1)}
function Ta(b,a,c,d){-1!==b.N&&clearTimeout(b.N);b.N=setTimeout(()=>Sa(b,a,c,d),48)}
function Pa(b){b=b.Ka;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ra(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.F(class extends self.S{constructor(b){super(b,"runtime");this.eb=!0;this.ab=!1;this.N=-1;this.Ka="any";this.Wa=this.Xa=!1;this.H=null;this.l=!1;this.bb="";this.Da=-1;this.K=this.aa=null;this.na=this.ma=0;this.$a=!1;this.Ga=b.B();this.Y=b.v();this.o=this.ca=0;b.h("canvas","update-size",d=>{var e=this.i;e.cb||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.eb&&(e.style.display="",this.eb=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","raster-svg-image",d=>Ha(d));b.h("runtime","get-svg-image-size",d=>Ia(d));b.h("runtime","set-target-orientation",d=>{this.Ka=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime",
"post-to-debugger",d=>Ja(d));b.h("runtime","go-to-script",d=>Ja(d));b.h("runtime","before-start-ticking",()=>Ka(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.H||(this.H=document.createElement("div"),this.H.id="inspectOutline",document.body.appendChild(this.H));var e=this.H;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.H&&(this.H.style.display="none")});b.h("runtime","enable-device-orientation",
()=>La(this));b.h("runtime","enable-device-motion",()=>Ma(this));b.h("runtime","add-stylesheet",d=>Na(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>this.xa(d));b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.qb()});b.h("runtime","export-to-video-progress",d=>Oa(this,d));b.h("runtime","exported-to-video",d=>{window.Qb({type:"exported-video",blob:d.blob,time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Qb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||I(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",J);window.addEventListener("gesturehold",J);c.addEventListener("selectstart",J);c.addEventListener("gesturehold",J);window.addEventListener("touchstart",J,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",J,{passive:!1}),c.addEventListener("pointerdown",J)):c.addEventListener("touchstart",J);this.$=
0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Da,{passive:!1});window.addEventListener("wheel",Da,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.ab){var d=this.B();var e=this.v();if(this.i.Pa()){if(this.$a){if(this.Ga===d&&e<this.Y){this.ca=this.Y-e;V(this,this.Y,this.ca);d=void 0;break a}0<this.ca&&(this.ca=0,V(this,e,this.ca))}this.Ga=d;this.Y=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,
isFullscreen:E.T()});this.i.sa()&&(-1!==this.N&&clearTimeout(this.N),Sa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",()=>M(this));window.addEventListener("fullscreenerror",d=>N(this,d));window.addEventListener("webkitfullscreenerror",d=>N(this,d));window.addEventListener("mozfullscreenerror",d=>N(this,d));if(b.sa())if(window.visualViewport){let d=
Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):I(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===
d?(E.ha(!0),M(this)):"exited-fullscreen"===d?(E.ha(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Ia=new Set;this.Nb=new WeakSet;this.Lb=!1}Na(){window.addEventListener("focus",()=>{k(this,"window-focus",null,G)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},G);this.$=0});window.addEventListener("focusin",a=>{a=a.target;(Ba.has(a.tagName.toLowerCase())||I(a))&&k(this,"keyboard-blur",
null,G)});window.addEventListener("keydown",a=>Qa(this,"keydown",a));window.addEventListener("keyup",a=>Qa(this,"keyup",a));window.addEventListener("dblclick",a=>P(this,"dblclick",a,F));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.o,pageX:a.pageX,pageY:a.pageY+this.o,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Q(a);
R(this,"pointerdown",a)}),this.i.A&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.aa=new self.pb(()=>{R(this,"pointermove",this.K);this.K=null}),this.aa.Za=!0,window.addEventListener("pointerrawupdate",a=>{this.K&&(this.ma+=this.K.movementX||0,this.na+=this.K.movementY||0);this.K=a;a=this.aa;if(-1===a.O){var c=Date.now(),d=c-a.ka,e=a.Kb;d>=e&&a.Za?(a.ka=c,a.W=!0,a.Ya(),a.W=!1):a.O=self.setTimeout(a.Pb,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>R(this,"pointermove",
a)),window.addEventListener("pointerup",a=>R(this,"pointerup",a)),window.addEventListener("pointercancel",a=>R(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Q(a);T(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>T(this,"pointermove",a)),window.addEventListener("mouseup",a=>T(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Q(a);U(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>U(this,"pointermove",a)),window.addEventListener("touchend",
a=>U(this,"pointerup",a)),window.addEventListener("touchcancel",a=>U(this,"pointercancel",a)));const b=()=>this.Aa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.kb()&&!this.i.Pa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{V(this,this.v(),
navigator.virtualKeyboard.boundingRect.height)}))}B(){return this.i.B()}v(){return this.i.v()}Aa(){var b=[...this.Ia];this.Ia.clear();if(!this.Lb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Nb.has(a)||this.Ia.add(a)})}xa(b){alert(b.message)}});"use strict";
async function pa(b){if(b.Jb)throw Error("already initialised");b.Jb=!0;var a=b.D.wa(("playable-ad"===b.D.g?b.D.M:"")+"dispatchworker.js");b.Ca=await b.D.qa(a,b.U,{name:"DispatchWorker"});a=new MessageChannel;b.Ea=a.port1;b.Ca.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ja=await ta(b)}function qa(b){return[b.Ea,b.Ja]}
async function ta(b){const a=b.fb.length;var c=b.D.wa(("playable-ad"===b.D.g?b.D.M:"")+"jobworker.js");c=await b.D.qa(c,b.U,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Ca.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.fb.push(c);return e.port1}
self.nb=class{constructor(b){this.D=b;this.U=b.m;this.U="preview"===b.g?this.U+"workers/":this.U+b.M;this.Mb=Math.min(navigator.hardwareConcurrency||2,16);this.Ca=null;this.fb=[];this.Ja=this.Ea=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.u({$b:!0,ac:"workermain.js",R:["scripts/c3runtime.js"],oa:[],La:"",Xb:"scripts/",Ma:["box2d.wasm.js"],hb:"html5"}));"use strict";
self.u.F(class extends self.S{constructor(b){super(b,"mouse");q(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function W(b){b.stopPropagation()}function X(b){const a=document.createElement("option");a.text=b;return a}function Ua(b){const a=b.selectedIndex,c=[];for(let d=0,e=b.length;d<e;++d)b.options[d].selected&&c.push(d);return{selectedIndex:a,selectedIndices:c}}
self.u.F(class extends self.ra{constructor(b){super(b,"list");t(this,"set-selected-index",(a,c)=>{a.selectedIndex=c.selectedIndex});t(this,"add-item",(a,c)=>{const d=c.index;c=X(c.text);0>d?a.add(c):a.add(c,d)});t(this,"remove-item",(a,c)=>{a.remove(c.index)});t(this,"set-item",(a,c)=>{a.options[c.index].text=c.text});t(this,"clear",a=>{a.innerHTML=""});t(this,"load-state",(a,c)=>{a.innerHTML="";for(const d of c.items)a.add(X(d));a.selectedIndex=c.selectedIndex;for(const d of c.selectedIndices)if(c=
a.options[d])c.selected=!0})}ea(b,a){const c=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position="absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;c||(f.size=2);for(const g of e)f.add(X(g));f.addEventListener("pointerdown",W);f.addEventListener("pointermove",W);f.addEventListener("pointerrawupdate",W);f.addEventListener("pointerup",W);f.addEventListener("mousedown",W);f.addEventListener("mouseup",W);f.addEventListener("click",
g=>{g.stopPropagation();v(this,"click",b,Ua(f))});f.addEventListener("dblclick",g=>{g.stopPropagation();v(this,"dblclick",b,Ua(f))});f.addEventListener("change",()=>r(this,"change",b,Ua(f)));a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.G(f,a);return f}G(b,a){b.title=a.title;b.disabled=!a.isEnabled;b.multiple=!!a.isMultiSelect}});"use strict";function Y(b){b.stopPropagation()}
self.u.F(class extends self.ra{constructor(b){super(b,"button")}ea(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Y);d.addEventListener("pointermove",
Y);d.addEventListener("pointerrawupdate",Y);d.addEventListener("pointerup",Y);d.addEventListener("mousedown",Y);d.addEventListener("mouseup",Y);d.addEventListener("keydown",Y);d.addEventListener("keyup",Y);c.addEventListener("click",()=>v(this,"click",b,{isChecked:c.checked}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.G(d,a);return d}va(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}G(b,a){const c="input"===b.tagName.toLowerCase()?b:b.firstChild;c.checked=a.isChecked;
c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";function Z(b){b.stopPropagation()}function Va(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.u.F(class extends self.ra{constructor(b){super(b,"text-input");t(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}ea(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",
Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Va);c.addEventListener("keyup",Va);c.addEventListener("click",e=>{e.stopPropagation();v(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();v(this,"dblclick",b)});c.addEventListener("input",()=>r(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.G(c,a);return c}G(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function Wa(){}function Xa(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Ya(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.u.F(class extends self.S{constructor(b){super(b,"browser");this.g="";q(this,[["get-initial-state",a=>this.ya(a)],["ready-for-sw-messages",()=>Xa(this)],["alert",a=>this.xa(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.za(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ya(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.ec||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.u.ha(!0),
this.i.Ba({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(Wa)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.g||"macos-wkwebview"===this.g)self.u.ha(!1),this.i.Ba({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Wa)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}ya(b){this.g=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}xa(b){alert(b.message)}za(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
async function Za(b){if(!b.I)try{b.I=await navigator.wakeLock.request("screen"),b.I.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.I=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
function $a(){var b=document.body;const a=b.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");b=getComputedStyle(b);b=[b.getPropertyValue("--temp-sai-top"),b.getPropertyValue("--temp-sai-right"),b.getPropertyValue("--temp-sai-bottom"),b.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);
return isFinite(c)?c:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return b}
self.u.F(class extends self.S{constructor(b){super(b,"platform-info");q(this,[["get-initial-state",()=>this.ya()],["request-wake-lock",()=>Za(this)],["release-wake-lock",()=>{this.I&&(this.I.release(),this.I=null)}]]);window.addEventListener("resize",()=>{k(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:$a()})});this.I=null}ya(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:$a(),supportsWakeLock:!!navigator.wakeLock}}});
